### ISSUE TITLE
Where to place attribution?

### ISSUE THREAD

**Issue by eugene-eeo** [nolanh/historic_events#3]
Hi @nolanh, I have been exposing the historic_events dataset through a REST API: https://github.com/datalib/chronicle. My question is where do I place the attribution; do I need to place them as footnotes in the README or the static page?

**Comment by nolanh** [comment]
Thanks for getting in touch (and for the contribution you made a while back). Your project looks awesome, by the way. As for the attribution line, you can put it in whichever place feels most natural to you. At the bottom of the README (even in a smaller font size, if you want) would be perfect as far as I'm concerned, and I don't believe Wikimedia has any specific requirements, either.

Feel free to reach out any time!
